name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd docs
          touch .env
          echo DOCS_BASE_URL=/Dolgozat1/docs/ >> .env
      - uses: actions/setup-node@v3.8.1
      - run: |
          cd docs && npm install && cd ..
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public